// apps/remote-dom-demo/src/app/remote-svelte/_demos/Files.svelte
<script>
  import {
    Button,
    CodeBlock,
    FileDropZone,
    FileField,
    Form,
    Heading,
    IconUpload,
    Section,
  } from "@mittwald/flow-remote-svelte-components";

  /*
   * The React page wires the fields through react-hook-form; there is no Svelte
   * integration, so this one reads the `FormData` the host collected — the
   * files cross the boundary either way, which is what the demo is about.
   */
  let submitted = $state(undefined);

  const submit = async (data) => {
    submitted = await Promise.all(
      [...data.entries()].map(async ([name, value]) =>
        value instanceof File
          ? {
              name,
              file: value.name,
              bytes: (await value.arrayBuffer()).byteLength,
            }
          : { name, value },
      ),
    );
  };
</script>

<Form onSubmit={(data) => void submit(data)}>
  <Section>
    <FileDropZone>
      <IconUpload />
      <Heading>Drop file here</Heading>
      <FileField name="fileDrop"><Button>Choose file</Button></FileField>
    </FileDropZone>
    <FileField name="files" multiple={true}
      ><Button>Choose file</Button></FileField
    >
    <Button type="submit">Submit</Button>
    <CodeBlock code={JSON.stringify(submitted, undefined, 2)} />
  </Section>
</Form>

// apps/remote-dom-demo/src/app/remote/files/page.tsx
"use client";

import {
  Button,
  FileDropZone,
  Section,
  FileField,
  IconUpload,
  Heading,
} from "@mittwald/flow-remote-react-components";

import {
  Form,
  Field,
} from "@mittwald/flow-remote-react-components/react-hook-form";
import { useForm } from "react-hook-form";

export default function Page() {
  const form = useForm({
    defaultValues: {
      fileDrop: [],
      files: [],
    },
  });

  return (
    <Form form={form} onSubmit={(data) => console.log("Submitted", data)}>
      <Section>
        <Field name="fileDrop">
          <FileDropZone>
            <IconUpload />
            <Heading>Drop file here</Heading>
            <FileField>
              <Button>Choose file</Button>
            </FileField>
          </FileDropZone>
        </Field>
        <Field name="files">
          <FileField>
            <Button>Choose file</Button>
          </FileField>
        </Field>
        <Button type={"submit"}>Submit</Button>
        <Button onPress={() => form.reset()}>Reset</Button>
      </Section>
    </Form>
  );
}
