// apps/remote-dom-demo/src/app/remote-vue/_demos/performance.tsx
/** @jsxImportSource @/app/remote-vue/_lib */
import {
  Alert,
  Button,
  Heading,
  Section,
  Text,
  TextField,
} from "@mittwald/flow-remote-vue-components";
import { defineComponent, onBeforeUnmount, onMounted, ref } from "vue";

/**
 * The Vue counterpart of `/remote/performance`.
 *
 * Every tick changes a prop on every alert, so the number in the field is the
 * number of remote properties that cross the boundary twice a second.
 */
export const PerformanceDemo = defineComponent({
  name: "PerformanceDemo",
  setup() {
    const elementCount = ref(100);
    const showElements = ref(true);
    const ticker = ref(0);

    let interval: ReturnType<typeof setInterval> | undefined;
    onMounted(() => {
      interval = setInterval(() => ticker.value++, 500);
    });
    onBeforeUnmount(() => clearInterval(interval));

    return () => (
      <Section>
        <TextField
          aria-label="Number of fleet alerts"
          onChange={(value: string) =>
            (elementCount.value = Number.parseInt(value))
          }
        />
        <Button onPress={() => (showElements.value = !showElements.value)}>
          Toggle fleet alerts
        </Button>
        {Number.isNaN(elementCount.value) || !showElements.value
          ? []
          : Array.from({ length: elementCount.value }, (_ignored, index) => (
              <Alert key={index}>
                <Heading>Fleet alert</Heading>
                <Text>Battle report {ticker.value}</Text>
              </Alert>
            ))}
      </Section>
    );
  },
});

// apps/remote-dom-demo/src/app/performance/page.tsx
"use client";
import { useEffect, useState } from "react";
import {
  Alert,
  Section,
  TextField,
  Heading,
  Text,
  Button,
} from "@mittwald/flow-remote-react-components";
import React from "react";

export default function Page() {
  const [elemCount, setElemCount] = useState(100);
  const [showElem, setShowElems] = useState(true);
  const [ticker, setTicker] = useState(0);

  useEffect(() => {
    const i = setInterval(() => {
      setTicker((cur) => cur + 1);
    }, 500);
    return () => {
      clearInterval(i);
    };
  }, []);

  return (
    <Section>
      <TextField onChange={(val) => setElemCount(Number.parseInt(val))} />
      <Button onPress={() => setShowElems((show) => !show)}>Toggle</Button>
      {isNaN(elemCount) || !showElem
        ? null
        : Array(elemCount)
            .fill(0)
            .map((_, index) => (
              <Alert key={index}>
                <Heading>Alert title</Heading>
                <Text>Alert text {ticker}</Text>
              </Alert>
            ))}
    </Section>
  );
}
