// apps/remote-dom-demo/src/app/remote-svelte/_demos/Popover.svelte
<script>
  import {
    Button,
    Popover,
    PopoverTrigger,
    Section,
    Text,
  } from "@mittwald/flow-remote-svelte-components";
</script>

<Section>
  <PopoverTrigger>
    <Button>Show battle station status</Button>
    <Popover>
      <Text>The Death Star is fully operational.</Text>
    </Popover>
  </PopoverTrigger>
</Section>

// apps/remote-dom-demo/src/app/popover/page.tsx
"use client";
import {
  Button,
  Popover,
  PopoverTrigger,
  Section,
} from "@mittwald/flow-remote-react-components";
import React from "react";

export default function Page() {
  return (
    <Section>
      <PopoverTrigger>
        <Button>Open</Button>
        <Popover>
          <>Popover content</>
        </Popover>
      </PopoverTrigger>
    </Section>
  );
}
