// apps/remote-dom-demo/src/app/remote/code-editor/page.tsx
"use client";
import {
  ActionGroup,
  CodeEditor,
  Section,
} from "@mittwald/flow-remote-react-components";
import { useForm } from "react-hook-form";
import {
  Field,
  Form,
  SubmitButton,
} from "@mittwald/flow-remote-react-components/react-hook-form";

export default function Page() {
  const form = useForm({
    defaultValues: {
      code: "hyperdrive_class=1.0",
    },
  });

  return (
    <Section>
      <Form
        form={form}
        onSubmit={async (data) => {
          console.log("Submitted:", data);
        }}
      >
        <Field
          name="code"
          rules={{
            validate: (val, ...asd) => {
              console.log("val", val, asd);
              return true;
            },
          }}
        >
          <CodeEditor language={"tsx"} />
        </Field>
        <ActionGroup>
          <SubmitButton>Save configuration</SubmitButton>
        </ActionGroup>
      </Form>
    </Section>
  );
}

// apps/remote-dom-demo/src/app/remote-svelte/_demos/CodeEditor.svelte
<script>
  import {
    ActionGroup,
    Button,
    CodeEditor,
    Form,
    Section,
  } from "@mittwald/flow-remote-svelte-components";

  /*
   * The React page wires the editor through react-hook-form; there is no Svelte
   * integration, so the value is held here and the form submits it.
   */
  let code = $state("hyperdrive_class=1.0");
</script>

<Section>
  <Form onSubmit={() => console.log("Submitted:", { code })}>
    <CodeEditor
      language="tsx"
      name="code"
      value={code}
      onChange={(next) => (code = next)}
    />
    <ActionGroup>
      <Button type="submit">Save configuration</Button>
    </ActionGroup>
  </Form>
</Section>
