// apps/remote-dom-demo/src/app/ext-bridge/page.tsx
"use client";
import { useExtBridge } from "@mittwald/ext-bridge/react";
import { CodeBlock, Section } from "@mittwald/flow-remote-react-components";

const BridgeInfo = () => {
  const bridge = useExtBridge();

  return <CodeBlock code={JSON.stringify(bridge.config)} />;
};

export default function Page() {
  return (
    <Section>
      <BridgeInfo />
    </Section>
  );
}

// apps/remote-dom-demo/src/app/remote-svelte/_demos/ExtBridge.svelte
<script>
  import { CodeBlock, Section } from "@mittwald/flow-remote-svelte-components";
  import { getConfig } from "@mittwald/ext-bridge/browser";

  /*
   * Ext-bridge itself is framework-agnostic — only its `useConfig` hook is
   * React. `getConfig()` is the same call without one.
   */
  let config = $state(undefined);

  $effect(() => {
    void getConfig().then((value) => (config = value));
  });
</script>

<Section>
  <CodeBlock code={JSON.stringify(config, undefined, 2)} />
</Section>
