// apps/remote-dom-demo/src/app/remote/ext-bridge/page.tsx
"use client";
import { useConfig } from "@mittwald/ext-bridge/react";
import {
  BrowserOnly,
  CodeBlock,
  Section,
} from "@mittwald/flow-remote-react-components";

const BridgeInfo = () => {
  const config = useConfig();

  return <CodeBlock code={JSON.stringify(config)} />;
};

export default function Page() {
  return (
    <Section>
      <BrowserOnly>
        <BridgeInfo />
      </BrowserOnly>
    </Section>
  );
}

// apps/remote-dom-demo/src/app/remote-svelte/_demos/ExtBridge.svelte
<script>
  import {
    BrowserOnly,
    CodeBlock,
    Section,
  } from "@mittwald/flow-remote-svelte-components";
  import { getConfig } from "@mittwald/ext-bridge/browser";

  /*
   * Ext-bridge itself is framework-agnostic — only its `useConfig` hook is
   * React. `getConfig()` is the same call without one.
   */
  let config = $state(undefined);

  $effect(() => {
    void getConfig().then((value) => (config = value));
  });
</script>

<Section>
  <BrowserOnly><CodeBlock code={JSON.stringify(config)} /></BrowserOnly>
</Section>
