// demos/remote-dom/src/app/remote/simple-form/page.tsx
"use client";
import {
  Section,
  CodeBlock,
  Form,
  TextField,
  Button,
} from "@mittwald/flow-remote-react-components";
import { useState } from "react";

export default function Page() {
  const [event, setEvent] = useState<unknown>();

  return (
    <Form onSubmit={setEvent}>
      <Section>
        <TextField name="test" aria-label="Test" />
        <Button type="submit">Submit</Button>
        <CodeBlock code={JSON.stringify(event, undefined, 2)} />
      </Section>
    </Form>
  );
}

// apps/remote-dom-demo/src/app/remote-svelte/_demos/SimpleForm.svelte
<script>
  import {
    Button,
    Form,
    Heading,
    Label,
    Section,
    Text,
    TextField,
  } from "@mittwald/flow-remote-svelte-components";

  let pilot = $state("");
  let submitted = $state("");
</script>

<Section>
  <Heading>Enlist a pilot</Heading>
  <Form
    onSubmit={(event) => {
      event.preventDefault?.();
      submitted = pilot;
    }}
  >
    <TextField value={pilot} onChange={(next) => (pilot = next)}>
      <Label>Call sign</Label>
    </TextField>
    <Button type="submit">Enlist</Button>
  </Form>
  {#if submitted}
    <Text>{submitted} reported for duty.</Text>
  {/if}
</Section>
