// apps/remote-dom-demo/src/app/remote-svelte/_demos/EventHandler.svelte
<script>
  import {
    Button,
    CodeBlock,
    Section,
    TextField,
  } from "@mittwald/flow-remote-svelte-components";

  /*
   * The listeners are the interesting half: the host dispatches the event, the
   * payload travels back through the connection, and plain Svelte state drives
   * the next render.
   */
  let event = $state(undefined);
</script>

<Section>
  <Button onPress={(value) => (event = value)} color="danger" variant="outline"
    >Fire proton torpedo</Button
  >
  <TextField onChange={(value) => (event = value)} aria-label="Mission name" />
  <CodeBlock code={JSON.stringify(event, undefined, 2)} />
</Section>

// apps/remote-dom-demo/src/app/remote/event-handler/page.tsx
"use client";
import {
  Button,
  CodeBlock,
  Section,
  TextField,
} from "@mittwald/flow-remote-react-components";
import { useState } from "react";

export default function Page() {
  const [event, setEvent] = useState<unknown>();

  return (
    <Section>
      <Button onPress={setEvent} color="danger" variant="outline">
        Fire proton torpedo
      </Button>
      <TextField onChange={setEvent} aria-label="Mission name" />
      <CodeBlock code={JSON.stringify(event, undefined, 2)} />
    </Section>
  );
}
