// apps/remote-dom-demo/src/app/remote-svelte/_demos/Files.svelte
<script>
  import {
    Button,
    CodeBlock,
    FileDropZone,
    FileField,
    Form,
    Heading,
    IconUpload,
    Section,
  } from "@mittwald/flow-remote-svelte-components";

  /*
   * The React page wires the fields through react-hook-form; there is no Svelte
   * integration, so this one reads the `FormData` the host collected — the
   * files cross the boundary either way, which is what the demo is about.
   */
  let submitted = $state(undefined);

  const submit = async (data) => {
    submitted = await Promise.all(
      [...data.entries()].map(async ([name, value]) =>
        value instanceof File
          ? {
              name,
              file: value.name,
              bytes: (await value.arrayBuffer()).byteLength,
            }
          : { name, value },
      ),
    );
  };
</script>

<Form onSubmit={(data) => void submit(data)}>
  <Section>
    <FileDropZone>
      <IconUpload />
      <Heading>Drop file here</Heading>
      <FileField name="fileDrop"><Button>Choose file</Button></FileField>
    </FileDropZone>
    <FileField name="files" multiple={true}
      ><Button>Choose file</Button></FileField
    >
    <Button type="submit">Submit</Button>
    <CodeBlock code={JSON.stringify(submitted, undefined, 2)} />
  </Section>
</Form>

// apps/remote-dom-demo/src/app/remote-vue/_demos/files.tsx
/** @jsxImportSource @/app/remote-vue/_lib */
import {
  Button,
  CodeBlock,
  FileDropZone,
  FileField,
  Form,
  Heading,
  IconUpload,
  Section,
} from "@mittwald/flow-remote-vue-components";
import { defineComponent, ref } from "vue";

/**
 * The Vue counterpart of `/remote/files`.
 *
 * The React page wires the fields through react-hook-form; there is no Vue
 * integration, so this one submits the `FormData` the host collected — the
 * files cross the boundary either way.
 */
export const FilesDemo = defineComponent({
  name: "FilesDemo",
  setup() {
    const submitted = ref<unknown>();

    const onSubmit = async (data: FormData) => {
      submitted.value = await Promise.all(
        Array.from(data.entries()).map(async ([name, value]) =>
          value instanceof File
            ? {
                name,
                file: value.name,
                bytes: (await value.arrayBuffer()).byteLength,
              }
            : { name, value },
        ),
      );
    };

    return () => (
      <Form onSubmit={onSubmit}>
        <Section>
          <FileDropZone>
            <IconUpload />
            <Heading>Drop file here</Heading>
            <FileField name="dropped">
              <Button>Choose file</Button>
            </FileField>
          </FileDropZone>
          <FileField name="files" multiple>
            <Button>Choose file</Button>
          </FileField>
          <Button type="submit">Submit</Button>
          <CodeBlock code={JSON.stringify(submitted.value, undefined, 2)} />
        </Section>
      </Form>
    );
  },
});
