// apps/remote-dom-demo/src/app/remote/list/page.tsx
"use client";

import { demoData } from "@/app/remote/list/demoData";
import {
  Action,
  ActionGroup,
  Avatar,
  BrowserOnly,
  Button,
  Content,
  ContextMenu,
  Heading,
  IconEmail,
  List,
  ListItemView,
  MenuItem,
  Modal,
  Section,
  Text,
  typedList,
  useModalController,
} from "@mittwald/flow-remote-react-components";

/**
 * The list demo, and the counterpart of `src/app/remote-vue/_demos/list.tsx`.
 *
 * The two pages describe the same list — an async loader that takes its time,
 * two filters, a search, two sortings, tiles, a table view, and a context menu
 * per item that opens that item's own modal. Keeping them the same is what
 * makes the React/Vue switch above them worth anything.
 */
export default function Page() {
  const DemoList = typedList<(typeof demoData)[number]>();

  return (
    <BrowserOnly>
      <Section>
        <List onAction={console.log} batchSize={10} aria-label="Demo">
          <DemoList.LoaderAsync>
            {() => {
              return new Promise((r) => {
                setTimeout(() => {
                  r({
                    data: demoData,
                    itemTotalCount: demoData.length,
                  });
                }, 1500);
              });
            }}
          </DemoList.LoaderAsync>

          <DemoList.Filter property="faction" name="Faction" mode="some" />
          {/* `secondary` keeps it out of the header — it lives in the
              all-filters modal, which is what puts that modal on desktop.
              `one` renders it there as a radio group. */}
          <DemoList.Filter
            property="homeworld"
            name="Homeworld"
            mode="one"
            priority="secondary"
          />
          <DemoList.Search />
          <DemoList.Sorting property="name" name="Name" direction="asc" />
          <DemoList.Sorting
            property="name"
            name="Name"
            direction="desc"
            directionName="descending"
          />

          {/* The href makes the host render a real anchor, so the browser's
              context menu, middle-click and modifier-click work on an item. */}
          <DemoList.Item
            textValue={(d) => d.name}
            href={(d) => `#${d.name}`}
            showTiles
          >
            {(d) => {
              const c = useModalController();
              return (
                <>
                  <ListItemView>
                    <Avatar>
                      <IconEmail />
                    </Avatar>
                    <Heading>
                      {d.name} ({d.faction})
                    </Heading>
                    <Text>{d.bio.slice(0, 100)}</Text>
                    <ContextMenu>
                      <MenuItem onAction={c.open}>
                        <IconEmail />
                        <Text>Send message</Text>
                      </MenuItem>
                    </ContextMenu>
                  </ListItemView>
                  <Modal controller={c}>
                    <Heading>{d.name}</Heading>
                    <Content>
                      <Section>
                        <Heading>{d.faction}</Heading>
                        <Text>{d.bio}</Text>
                      </Section>
                    </Content>
                    <ActionGroup>
                      <Action closeModal>
                        <Button>Cancel</Button>
                      </Action>
                    </ActionGroup>
                  </Modal>
                </>
              );
            }}
          </DemoList.Item>

          <DemoList.Table>
            <DemoList.TableHeader>
              <DemoList.TableColumn>Name</DemoList.TableColumn>
            </DemoList.TableHeader>
            <DemoList.TableBody>
              <DemoList.TableRow>
                <DemoList.TableCell>{(d) => d.name}</DemoList.TableCell>
              </DemoList.TableRow>
            </DemoList.TableBody>
          </DemoList.Table>
        </List>
      </Section>
    </BrowserOnly>
  );
}

// apps/remote-dom-demo/src/app/remote-vue/_demos/list.tsx
/** @jsxImportSource @/app/remote-vue/_lib */
import { demoData, type DemoCharacter } from "@/app/remote/list/demoData";
import {
  Action,
  ActionGroup,
  Avatar,
  Button,
  Content,
  ContextMenu,
  Heading,
  IconEmail,
  List,
  ListFilter,
  ListItem,
  ListItemView,
  ListLoaderAsync,
  ListSearch,
  ListSorting,
  ListTableCell,
  ListTableColumn,
  MenuItem,
  Modal,
  Section,
  Text,
  useModalController,
} from "@mittwald/flow-remote-vue-components";
import { defineComponent, type PropType } from "vue";

/**
 * The `list` demo as a Vue remote app — the counterpart of
 * `src/app/remote/list/page.tsx`.
 *
 * Deliberately the same list: an async loader that takes its time, two filters,
 * a search, two sortings, tiles, a table view, and a context menu per item that
 * opens that item's own modal.
 */
const loadCharacters = () =>
  new Promise<{ data: DemoCharacter[]; itemTotalCount: number }>((resolve) => {
    setTimeout(
      () => resolve({ data: demoData, itemTotalCount: demoData.length }),
      1500,
    );
  });

/**
 * One item, as a component rather than a render function.
 *
 * The modal's controller has to survive the item's re-renders, and a slot
 * function has nowhere to keep one — React's page calls `useModalController()`
 * inside its item render because a hook there is a hook in the component that
 * renders it. The Vue equivalent of that is a component with a `setup()`.
 */
const CharacterItem = defineComponent({
  name: "CharacterItem",

  props: {
    data: { type: Object as PropType<DemoCharacter>, required: true },
  },

  setup(props) {
    const controller = useModalController();

    return () => [
      <ListItemView>
        <Avatar>
          <IconEmail />
        </Avatar>
        <Heading>
          {props.data.name} ({props.data.faction})
        </Heading>
        <Text>{props.data.bio.slice(0, 100)}</Text>
        <ContextMenu>
          <MenuItem onAction={controller.open}>
            <IconEmail />
            <Text>Send message</Text>
          </MenuItem>
        </ContextMenu>
      </ListItemView>,
      <Modal controller={controller}>
        <Heading>{props.data.name}</Heading>
        <Content>
          <Section>
            <Heading>{props.data.faction}</Heading>
            <Text>{props.data.bio}</Text>
          </Section>
        </Content>
        <ActionGroup>
          <Action closeModal>
            <Button>Cancel</Button>
          </Action>
        </ActionGroup>
      </Modal>,
    ];
  },
});

export const ListDemo = defineComponent({
  name: "ListDemo",

  setup: () => () => (
    <Section>
      <List
        aria-label="Demo"
        batchSize={10}
        onAction={(data: DemoCharacter) => console.log(data)}
      >
        <ListLoaderAsync loader={loadCharacters} />

        <ListFilter property="faction" name="Faction" mode="some" />
        <ListFilter
          property="homeworld"
          name="Homeworld"
          mode="some"
          priority="secondary"
        />
        <ListSearch />
        <ListSorting property="name" name="Name" direction="asc" />
        <ListSorting
          property="name"
          name="Name"
          direction="desc"
          directionName="descending"
        />

        {/* An href makes the host render a real anchor, so middle-click and
            the browser's own context menu work on an item. */}
        <ListItem
          textValue={(data: DemoCharacter) => data.name}
          href={(data: DemoCharacter) => `#${data.name}`}
          showTiles
        >
          {{
            default: ({ data }: { data: DemoCharacter }) => (
              <CharacterItem data={data} key={data.id} />
            ),
          }}
        </ListItem>

        <ListTableColumn>Name</ListTableColumn>
        <ListTableCell>
          {{ default: ({ data }: { data: DemoCharacter }) => data.name }}
        </ListTableCell>
      </List>
    </Section>
  ),
});
