// apps/remote-dom-demo/src/app/remote/list-selection/page.tsx
"use client";

import {
  Avatar,
  Badge,
  BrowserOnly,
  Content,
  ContextMenu,
  Heading,
  Initials,
  ListItemView,
  MenuItem,
  Section,
  Text,
  typedList,
} from "@mittwald/flow-remote-react-components";

interface Crew {
  id: string;
  name: string;
  role: string;
  status: string;
}

const crew: Crew[] = [
  { id: "1", name: "Luke Skywalker", role: "Jedi Master", status: "active" },
  { id: "2", name: "Leia Organa", role: "Rebel Pilot", status: "unavailable" },
  { id: "3", name: "Han Solo", role: "Smuggler", status: "active" },
];

export default function Page() {
  const List = typedList<Crew>();

  return (
    <BrowserOnly>
      <Section>
        <List.List
          aria-label="Crew"
          getItemId={(item) => item.id}
          selectedKeys={["2"]}
          selectionMode="multiple"
        >
          <List.StaticData data={crew} />
          <List.Filter property="role" name="Role" />
          <List.Sorting property="name" name="Alphabetical" defaultEnabled />
          <List.Item textValue={(item) => item.name}>
            {(item) => (
              <ListItemView>
                <Avatar>
                  <Initials>{item.name}</Initials>
                </Avatar>
                <Heading>
                  {item.name}
                  {item.status === "active" && <Badge>Active</Badge>}
                </Heading>
                <Text>{item.role}</Text>
                <Content>{item.role}</Content>
                <ContextMenu>
                  <MenuItem>Show details</MenuItem>
                  <MenuItem>Delete</MenuItem>
                </ContextMenu>
              </ListItemView>
            )}
          </List.Item>
        </List.List>
      </Section>
      <Section>
        <Heading>Table view</Heading>
        <List.List
          defaultViewMode="table"
          aria-label="Crew table"
          getItemId={(item) => item.id}
          selectedKeys={["1", "2"]}
          selectionMode="multiple"
        >
          <List.StaticData data={crew} />
          <List.Table>
            <List.TableHeader>
              <List.TableColumn>Name</List.TableColumn>
              <List.TableColumn>Role</List.TableColumn>
            </List.TableHeader>
            <List.TableBody>
              <List.TableRow>
                <List.TableCell>{(item) => item.name}</List.TableCell>
                <List.TableCell>{(item) => item.role}</List.TableCell>
              </List.TableRow>
            </List.TableBody>
          </List.Table>
        </List.List>
      </Section>
    </BrowserOnly>
  );
}

// apps/remote-dom-demo/src/app/remote-vue/_demos/listSelection.tsx
/** @jsxImportSource @/app/remote-vue/_lib */
import {
  Avatar,
  Badge,
  Content,
  ContextMenu,
  Heading,
  Initials,
  List,
  ListFilter,
  ListItem,
  ListItemView,
  ListSorting,
  ListStaticData,
  ListTableCell,
  ListTableColumn,
  MenuItem,
  Section,
  Text,
} from "@mittwald/flow-remote-vue-components";
import { defineComponent } from "vue";

/**
 * The `list-selection` demo as a Vue remote app — the counterpart of
 * `src/app/remote/list-selection/page.tsx`.
 *
 * Selection is the host's: `selectionMode`, `selectedKeys` and `getItemId`
 * reach the grid list and the table untouched, which is also what the React
 * list does with them. The second list shows that the table view carries them
 * too.
 */
interface Crew {
  id: string;
  name: string;
  role: string;
  status: string;
}

const crew: Crew[] = [
  { id: "1", name: "Luke Skywalker", role: "Jedi Master", status: "active" },
  { id: "2", name: "Leia Organa", role: "Rebel Pilot", status: "unavailable" },
  { id: "3", name: "Han Solo", role: "Smuggler", status: "active" },
];

const getItemId = (item: Crew) => item.id;

export const ListSelectionDemo = defineComponent({
  name: "ListSelectionDemo",

  setup: () => () => [
    <Section>
      <List
        aria-label="Crew"
        getItemId={getItemId}
        selectedKeys={["2"]}
        selectionMode="multiple"
      >
        <ListStaticData data={crew} />
        <ListFilter property="role" name="Role" />
        <ListSorting property="name" name="Alphabetical" defaultEnabled />
        <ListItem textValue={(item: Crew) => item.name}>
          {{
            default: ({ data }: { data: Crew }) => (
              <ListItemView>
                <Avatar>
                  <Initials>{data.name}</Initials>
                </Avatar>
                <Heading>
                  {data.name}
                  {data.status === "active" ? <Badge>Active</Badge> : null}
                </Heading>
                <Text>{data.role}</Text>
                <Content>{data.role}</Content>
                <ContextMenu>
                  <MenuItem>Show details</MenuItem>
                  <MenuItem>Delete</MenuItem>
                </ContextMenu>
              </ListItemView>
            ),
          }}
        </ListItem>
      </List>
    </Section>,

    <Section>
      <Heading>Table view</Heading>
      <List
        aria-label="Crew table"
        defaultViewMode="table"
        getItemId={getItemId}
        selectedKeys={["1", "2"]}
        selectionMode="multiple"
      >
        <ListStaticData data={crew} />
        {/* Flat, not nested: the list reads its own children. */}
        <ListTableColumn>Name</ListTableColumn>
        <ListTableColumn>Role</ListTableColumn>
        <ListTableCell>
          {{ default: ({ data }: { data: Crew }) => data.name }}
        </ListTableCell>
        <ListTableCell>
          {{ default: ({ data }: { data: Crew }) => data.role }}
        </ListTableCell>
      </List>
    </Section>,
  ],
});
