// apps/remote-dom-demo/src/app/remote/suspense/page.tsx
"use client";
import {
  BrowserOnly,
  Button,
  Heading,
  Section,
  Text,
  TextField,
} from "@mittwald/flow-remote-react-components";
import { getAsyncResource } from "@mittwald/react-use-promise";
import { type FC, Suspense, useState } from "react";

const getAsyncValue = (sleepMs: number) =>
  new Promise<number>((res) => {
    setTimeout(() => res(sleepMs), sleepMs);
  });

interface Props {
  sleepMs: number;
  label: string;
}

const EnhancedDataComponent: FC<Props> = (props) => {
  const asyncResource = getAsyncResource(getAsyncValue, [props.sleepMs]);

  const value = asyncResource.use({
    keepValueWhileLoading: false,
  });

  const [buttonPressState, setButtonPressState] = useState(0);

  return (
    <Section>
      <Heading>{props.label}</Heading>
      <Text>Reached in {value} seconds</Text>
      <Button onPress={() => asyncResource.refresh()}>Reconnect</Button>
      <Button
        color="secondary"
        variant="soft"
        onPress={() => setButtonPressState((p) => p + 1)}
      >
        <Text>Pinged {buttonPressState}x</Text>
      </Button>
      <TextField aria-label="Outpost name" />
    </Section>
  );
};

export default function Page() {
  return (
    <BrowserOnly>
      <Suspense fallback={<Heading>Contacting Tatooine…</Heading>}>
        <EnhancedDataComponent label="Tatooine outpost" sleepMs={1500} />
      </Suspense>
      <Suspense fallback={<Heading>Contacting Hoth…</Heading>}>
        <EnhancedDataComponent label="Hoth outpost" sleepMs={1100} />
      </Suspense>
      <Suspense fallback={<Heading>Contacting Endor…</Heading>}>
        <EnhancedDataComponent label="Endor outpost" sleepMs={1700} />
      </Suspense>
    </BrowserOnly>
  );
}

// apps/remote-dom-demo/src/app/remote-vue/_demos/suspense.tsx
/** @jsxImportSource @/app/remote-vue/_lib */
import {
  Button,
  Heading,
  Section,
  Text,
  TextField,
} from "@mittwald/flow-remote-vue-components";
import { defineComponent, ref, Suspense } from "vue";

const contact = (sleepMs: number) =>
  new Promise<number>((resolve) => setTimeout(() => resolve(sleepMs), sleepMs));

interface OutpostProps {
  label: string;
  sleepMs: number;
}

/**
 * Suspends until the outpost answers. Vue's `<Suspense>` waits for an async
 * `setup`, the way React's waits for a thrown promise.
 */
const Outpost = defineComponent({
  name: "Outpost",
  props: {
    label: { type: String, required: true },
    sleepMs: { type: Number, required: true },
  },
  async setup(props: OutpostProps) {
    const value = ref(await contact(props.sleepMs));
    const pings = ref(0);
    const isReconnecting = ref(false);

    const reconnect = async () => {
      isReconnecting.value = true;
      value.value = await contact(props.sleepMs);
      isReconnecting.value = false;
    };

    return () => (
      <Section>
        <Heading>{props.label}</Heading>
        <Text>Reached in {value.value} ms</Text>
        <Button
          isPending={isReconnecting.value}
          onPress={() => void reconnect()}
        >
          Reconnect
        </Button>
        <Button color="secondary" variant="soft" onPress={() => pings.value++}>
          <Text>Pinged {pings.value}x</Text>
        </Button>
        <TextField aria-label="Outpost name" />
      </Section>
    );
  },
});

const suspended = (label: string, sleepMs: number) => (
  <Suspense>
    {{
      default: () => <Outpost label={label} sleepMs={sleepMs} />,
      fallback: () => <Heading>Contacting {label}…</Heading>,
    }}
  </Suspense>
);

/**
 * The Vue counterpart of `/remote/suspense`.
 *
 * The fallback is a remote tree too, so the host renders it — the loading state
 * crosses the boundary like everything else, and the swap is one more mutation
 * batch.
 */
export const SuspenseDemo = defineComponent({
  name: "SuspenseDemo",
  setup: () => () => [
    suspended("Tatooine outpost", 1500),
    suspended("Hoth outpost", 1100),
    suspended("Endor outpost", 1700),
  ],
});
