// packages/remote-svelte-components/src/components/CountryOptions.svelte
<script lang="ts" module>
  import { all, type CountryData } from "country-codes-list";
  import { uniqueBy } from "remeda";

  export type Country = CountryData & {
    name: string;
    code: string;
  };

  export type CountryFilterFn = (country: Country) => boolean;
  export type CountrySortFn = (left: Country, right: Country) => number;

  // see https://github.com/Synergy-Shock/country-codes-list/issues/37
  const uniqueCountries = uniqueBy(all(), (c) => c.countryCode);

  const defaultSortBy: CountrySortFn = (left, right) =>
    left.name.localeCompare(right.name);
  const defaultFilterBy: CountryFilterFn = () => true;
</script>

<script lang="ts">
  import Option from "../auto-generated/Option.svelte";
  import { useLanguage } from "../lib/remoteContext.svelte.js";

  /**
   * The countries of the world, as `Option`s for a `Select` or `ComboBox`.
   *
   * Flow ships the country names as locale files. Here they come from
   * `Intl.DisplayNames` in the host's language, which is the same data every
   * browser already carries — no translation files to keep in sync, at the
   * price of the browser's spelling rather than Flow's.
   */
  interface Props {
    filterBy?: CountryFilterFn;
    sortBy?: CountrySortFn;
  }

  const {
    filterBy = defaultFilterBy,
    sortBy = defaultSortBy,
  }: Props = $props();

  const language = useLanguage();

  const countries = $derived.by(() => {
    const displayNames = new Intl.DisplayNames([language.current ?? "en-US"], {
      type: "region",
    });

    return uniqueCountries
      .map((countryData) => ({
        ...countryData,
        code: countryData.countryCode,
        name:
          displayNames.of(countryData.countryCode) ?? countryData.countryNameEn,
      }))
      .filter(filterBy)
      .sort(sortBy);
  });
</script>

{#each countries as country (country.code)}<Option
    value={country.code}
    textValue={country.name}
  >{country.name}</Option>{/each}

// packages/components/src/components/CountryOptions/CountryOptions.tsx
import type { FC, PropsWithChildren } from "react";
import { useMemo } from "react";
import type { ListBoxProps } from "react-aria-components";
import { useLocalizedStringFormatter } from "@/components/TranslationProvider/useLocalizedStringFormatter";
import type { FlowComponentProps } from "@/lib/componentFactory/flowComponent";
import locales from "./locales/*.locale.json";
import { all, type CountryData } from "country-codes-list";
import OptionView from "@/views/OptionView";
import { uniqueBy } from "remeda";

export type Country = CountryData & {
  name: string;
  code: string;
};

export type CountryFilterFn = (country: Country) => boolean;
export type CountrySortFn = (left: Country, right: Country) => number;

export interface CountryOptionsProps<T = object>
  extends
    PropsWithChildren<Omit<ListBoxProps<T>, "children">>,
    FlowComponentProps {
  filterBy?: CountryFilterFn;
  sortBy?: CountrySortFn;
}

const defaultSortBy: CountrySortFn = (left, right) =>
  left.name.localeCompare(right.name);
const defaultFilterBy: CountryFilterFn = () => true;

// see https://github.com/Synergy-Shock/country-codes-list/issues/37
const uniqueCountries = uniqueBy(all(), (c) => c.countryCode);

export const CountryOptions: FC<CountryOptionsProps> = (props) => {
  const { filterBy = defaultFilterBy, sortBy = defaultSortBy } = props;
  const stringFormatter = useLocalizedStringFormatter(
    locales,
    "CountryOptions",
  );

  return useMemo(() => {
    return uniqueCountries
      .map((countryData) => ({
        ...countryData,
        code: countryData.countryCode,
        name: stringFormatter.format(`countryCode.${countryData.countryCode}`),
      }))
      .filter(filterBy)
      .sort(sortBy)
      .map((country) => (
        <OptionView
          key={country.countryNameEn}
          value={country.countryCode}
          textValue={country.name}
        >
          {country.name}
        </OptionView>
      ));
  }, [stringFormatter]);
};

export default CountryOptions;
